import assert from 'node:assert/strict';
import { parseAssistantReply, validateAssistantAction, commandDraftBytes, summarizeChannel } from '../src/core/assistant/debugAssistant';
import { aiServiceNeedsKey } from '../src/services/ai';

const command = validateAssistantAction({ type: 'command_draft', title: '检查回显', input: 'AA 55', encoding: 'hex', escapeText: false, lineEnding: 'none' }, []);
assert.equal(command.type, 'command_draft');
if (command.type === 'command_draft') assert.deepEqual([...commandDraftBytes(command)], [0xaa, 0x55]);
const text = validateAssistantAction({ type: 'command_draft', title: '用户提供的协议', input: ' PING\\n', encoding: 'text', escapeText: true, lineEnding: 'crlf' }, []);
if (text.type === 'command_draft') assert.deepEqual([...commandDraftBytes(text)], [32, 80, 73, 78, 71, 10]);
for (const encoding of ['text', 'ascii', undefined]) assert.throws(() => validateAssistantAction({ type: 'command_draft', title: '格式错误', input: 'AA ZZ', encoding, lineEnding: 'none' }, []));
assert.throws(() => validateAssistantAction({ type: 'command_draft', title: '残缺字节', input: 'A', encoding: 'hex', escapeText: false, lineEnding: 'none' }, []));
assert.throws(() => validateAssistantAction({ type: 'send_now', title: '越权发送' }, []));
assert.throws(() => validateAssistantAction({ type: 'display_widget', title: '控制设备', widget: 'slider', channels: ['temperature'], unit: '' }, ['temperature']));
assert.throws(() => validateAssistantAction({ type: 'display_widget', title: '不存在通道', widget: 'chart', channels: ['speed'], unit: '' }, ['temperature']));
assert.throws(() => validateAssistantAction({ type: 'display_widget', title: '重复', widget: 'chart', channels: ['x', 'x'], unit: '' }, ['x']));
const widget = validateAssistantAction({ type: 'display_widget', title: '温度', widget: 'number', channels: ['temperature'], unit: '℃', enabled: true, command_template: 'RST' }, ['temperature']);
assert.deepEqual(widget, { type: 'display_widget', title: '温度', widget: 'number', channels: ['temperature'], unit: '℃' });
assert.throws(() => validateAssistantAction({ type: 'protocol', title: '无效通道', config: { type: 'justfloat', channels: 128 } }, []));
assert.throws(() => validateAssistantAction({ type: 'protocol', title: '类型无效', config: { type: 'rawdata', mode: 'decode', channels: 1, format: 'made_up' } }, []));
assert.deepEqual(validateAssistantAction({ type: 'protocol', title: '文本', config: { type: 'firewater', api_key: 'must-not-survive' } }, []), { type: 'protocol', title: '文本', config: { type: 'firewater' } });
const reply = parseAssistantReply(JSON.stringify({ explanation: '先核对接线', uncertainties: ['未连接设备'], actions: [widget, { type: 'write', title: '强制执行' }] }), ['temperature']);
assert.equal(reply.actions.length, 1); assert.equal(reply.rejected.length, 1);
assert.equal(parseAssistantReply('```json\n' + JSON.stringify({ explanation: '没有依据', actions: [] }) + '\n```', []).actions.length, 0);
assert.equal(parseAssistantReply('建议发送 RESET，但这只是文字', []).actions.length, 0);
assert.throws(() => parseAssistantReply('x'.repeat(65537), []));
assert.deepEqual(summarizeChannel('x', [1, 2, 3], [NaN, -2, 5]), { id: 'x', count: 3, from: 1, to: 3, min: -2, max: 5, last: 5, invalid: 1 });
assert.equal(summarizeChannel('empty', [], []).last, null);
assert.equal(aiServiceNeedsKey({ provider: 'custom', api_url: 'http://127.0.0.1:8080/v1' }), false);
assert.equal(aiServiceNeedsKey({ provider: 'custom', api_url: 'http://[::1]:8080/v1' }), false);
assert.equal(aiServiceNeedsKey({ provider: 'custom', api_url: 'https://localhost.example.com/v1' }), true);
assert.equal(aiServiceNeedsKey({ provider: 'openai', api_url: 'https://api.openai.com/v1' }), true);
console.log('Task assistant: strict drafts, exact bytes, channel references, protocol validation and untrusted outputs passed.');
